application: eloquent-walker-820 
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:

- url: /favicon.ico
  static_dir: static/favicon.ico

- url: /static
  static_dir: static

- url: /.*
  script: oingfolio.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  
